import { test,expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { PDFDocument } from 'pdf-lib';
test.beforeAll(()=>{execFileSync('node',['--import','tsx','scripts/demo.ts'],{env:{...process.env,DATABASE_PATH:process.env.E2E_DATABASE_PATH,UPLOAD_DIR:'/tmp/picking-e2e-uploads',DEMO_PASSWORD:'testpassword123'},stdio:'pipe'});});
test('admin manages SKU photo/location, staff, manual orders and AI-failure fallback',async({page})=>{
 await page.goto('/login');await page.getByLabel('Username').fill('admin.demo');await page.getByLabel('Password',{exact:true}).fill('testpassword123');await page.getByRole('button',{name:'Masuk ke gudang'}).click();await expect(page.getByRole('heading',{name:'Ringkasan gudang'})).toBeVisible();
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/picking-dashboard.png',fullPage:true});
 await page.goto('/admin/products');await page.getByLabel('SKU produk').fill('000C');await page.getByLabel('Nama barang',{exact:true}).fill('Produk contoh');
 await page.getByLabel('Foto barang').setInputFiles({name:'item.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXwAAAABJRU5ErkJggg==','base64')});
 await page.getByLabel('Rak',{exact:true}).selectOption('4');await page.getByLabel('Ambalan',{exact:true}).selectOption('F');await page.getByRole('button',{name:'Simpan barang'}).click();await expect(page.getByRole('status')).toContainText('berhasil disimpan');await expect(page.getByRole('img',{name:'Produk contoh'})).toBeVisible();
 await page.getByRole('button').filter({hasText:'Produk contoh'}).click();await page.getByLabel('Rak',{exact:true}).selectOption('2');await page.getByRole('button',{name:'Simpan barang'}).click();await expect(page.getByRole('status')).toContainText('berhasil disimpan');await expect(page.getByRole('button').filter({hasText:'Produk contoh'})).toContainText('Rak 2');
 await page.goto('/admin/staff');await page.getByLabel('Nama staff').fill('Staff baru');await page.getByLabel('Username staff').fill('staff.baru');await page.getByLabel('Password awal').fill('testpassword123');await page.getByRole('button',{name:'Tambah staff',exact:true}).click();await expect(page.getByText('Staff baru',{exact:true})).toBeVisible();
 await page.goto('/admin/orders/new');await page.getByLabel('Nomor order',{exact:true}).fill('MANUAL-001');await page.getByLabel('SKU / barang 1',{exact:true}).selectOption({label:'000C — Produk contoh'});await page.getByLabel('Qty',{exact:true}).fill('2');await page.getByRole('button',{name:'Simpan order'}).click();await expect(page.getByRole('heading',{name:'MANUAL-001',exact:true})).toBeVisible();
 await page.goto('/admin/import');const pdf=await PDFDocument.create();pdf.addPage();await page.getByLabel('PDF order',{exact:true}).setInputFiles({name:'resi.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});await page.getByRole('button',{name:'Baca PDF dengan AI'}).click();await expect(page.getByRole('heading',{name:'Input manual dari PDF'})).toBeVisible();await page.getByLabel('Nomor order',{exact:true}).fill('FALLBACK-001');await page.getByLabel('SKU / barang 1',{exact:true}).selectOption({label:'000C — Produk contoh'});await page.getByRole('button',{name:'Simpan order'}).click();await expect(page.getByRole('heading',{name:'FALLBACK-001',exact:true})).toBeVisible();
});

test('admin paginates master products, keeps rack/search filters and edits page-two stock',async({page})=>{
 await page.goto('/login');await page.getByLabel('Username').fill('admin.demo');await page.getByLabel('Password',{exact:true}).fill('testpassword123');await page.getByRole('button',{name:'Masuk ke gudang'}).click();await expect(page.getByRole('heading',{name:'Ringkasan gudang'})).toBeVisible();
 for(let i=0;i<25;i++)expect((await page.request.post('/api/products',{headers:{origin:'http://127.0.0.1:3010'},data:{sku:`ZZADMIN-${String(i).padStart(2,'0')}`,name:`Admin pagination ${i}`,active:true,locations:[{rack:1,shelf:'A',quantity:1},{rack:3,shelf:'B',quantity:2}]}})).ok()).toBeTruthy();
 const all=await (await page.request.get('/api/products')).json(),rackCount=all.filter((p:{active:boolean;locations:{rack:number}[]})=>p.active&&p.locations.some(l=>l.rack===3)).length;
 await page.goto('/admin/products?search=ZZADMIN');await expect(page.locator('.catalog-row')).toHaveCount(20);await expect(page.getByText('Halaman 1 dari 2',{exact:true})).toBeVisible();const card=page.getByRole('button',{name:'Filter Rak 3',exact:true});await expect(card).toContainText(`${rackCount} SKU`);await card.click();await expect(page).toHaveURL(/rack=3/);await expect(page.locator('.catalog-row')).toHaveCount(20);
 await page.getByRole('link',{name:'Berikutnya',exact:true}).click();await expect(page.locator('.catalog-row')).toHaveCount(5);await expect(page.getByText('Halaman 2 dari 2',{exact:true})).toBeVisible();expect(new URL(page.url()).searchParams.get('rack')).toBe('3');expect(new URL(page.url()).searchParams.get('search')).toBe('ZZADMIN');await expect(card).toContainText(`${rackCount} SKU`);
 const row=page.locator('.catalog-row').filter({hasText:'ZZADMIN-24'});await row.click();await expect(page.getByLabel('SKU produk')).toHaveValue('ZZADMIN-24');await page.getByLabel('Quantity',{exact:true}).fill('11');await page.getByRole('button',{name:'Simpan barang',exact:true}).click();await expect(page.getByRole('status')).toContainText('berhasil disimpan');await expect(row).toContainText('Total: 13 unit');
 await page.getByLabel('Cari SKU atau nama barang').fill('ZZADMIN-00');await page.getByRole('button',{name:'Cari produk',exact:true}).click();await expect(page.locator('.catalog-row')).toHaveCount(1);await expect(page.getByText('Halaman 1 dari 1',{exact:true})).toBeVisible();expect(new URL(page.url()).searchParams.get('rack')).toBe('3');
 await page.getByLabel('Cari SKU atau nama barang').fill('not-a-product');await page.getByRole('button',{name:'Cari produk',exact:true}).click();await expect(page.getByText('Barang tidak ditemukan',{exact:true})).toBeVisible();
 await page.goto('/admin/products?search=ZZADMIN&rack=3&page=2');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/picking-admin-pagination-mobile.png',fullPage:true});
});
