import { test,expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { PDFDocument } from 'pdf-lib';
test.beforeAll(()=>{execFileSync('node',['--import','tsx','scripts/demo.ts'],{env:{...process.env,DATABASE_PATH:process.env.E2E_DATABASE_PATH,UPLOAD_DIR:'/tmp/picking-e2e-uploads',DEMO_PASSWORD:'testpassword123'},stdio:'pipe'});});
test('admin manages SKU photo/location, staff, manual orders and AI-failure fallback',async({page})=>{
 await page.goto('/login');await page.getByLabel('Username').fill('admin.demo');await page.getByLabel('Password',{exact:true}).fill('testpassword123');await page.getByRole('button',{name:'Masuk ke gudang'}).click();await expect(page.getByRole('heading',{name:'Ringkasan gudang'})).toBeVisible();
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/picking-dashboard.png',fullPage:true});
 await page.goto('/admin/products');await page.getByLabel('SKU produk').fill('000C');await page.getByLabel('Nama barang',{exact:true}).fill('Produk contoh');
 await page.getByLabel('Foto barang').setInputFiles({name:'item.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXwAAAABJRU5ErkJggg==','base64')});
 await page.getByLabel('Rak',{exact:true}).selectOption('4');await page.getByLabel('Ambalan',{exact:true}).selectOption('F');await page.getByRole('button',{name:'Simpan barang'}).click();await expect(page.getByRole('status')).toContainText('berhasil disimpan');await expect(page.getByRole('img',{name:'Produk contoh'})).toBeVisible();
 await page.getByRole('button').filter({hasText:'Produk contoh'}).click();await page.getByLabel('Rak',{exact:true}).selectOption('2');await page.getByRole('button',{name:'Simpan barang'}).click();await expect(page.getByRole('status')).toContainText('berhasil disimpan');await expect(page.getByRole('button').filter({hasText:'Produk contoh'})).toContainText('Rak 2');
 await page.goto('/admin/staff');await page.getByLabel('Nama staff').fill('Staff baru');await page.getByLabel('Username staff').fill('staff.baru');await page.getByLabel('Password awal').fill('testpassword123');await page.getByRole('button',{name:'Tambah staff',exact:true}).click();await expect(page.getByText('Staff baru',{exact:true})).toBeVisible();
 await page.goto('/admin/orders/new');await page.getByLabel('Nomor order',{exact:true}).fill('MANUAL-001');await page.getByLabel('SKU / barang 1',{exact:true}).selectOption({label:'000C — Produk contoh'});await page.getByLabel('Qty',{exact:true}).fill('2');await page.getByRole('button',{name:'Simpan order'}).click();await expect(page.getByRole('heading',{name:'MANUAL-001',exact:true})).toBeVisible();
 await page.goto('/admin/import');const pdf=await PDFDocument.create();pdf.addPage();await page.getByLabel('PDF order',{exact:true}).setInputFiles({name:'resi.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});await page.getByRole('button',{name:'Baca PDF dengan AI'}).click();await expect(page.getByRole('heading',{name:'Input manual dari PDF'})).toBeVisible();await page.getByLabel('Nomor order',{exact:true}).fill('FALLBACK-001');await page.getByLabel('SKU / barang 1',{exact:true}).selectOption({label:'000C — Produk contoh'});await page.getByRole('button',{name:'Simpan order'}).click();await expect(page.getByRole('heading',{name:'FALLBACK-001',exact:true})).toBeVisible();
});
