import { test,expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
test.beforeAll(()=>{execFileSync('node',['--import','tsx','scripts/demo.ts'],{env:{...process.env,DATABASE_PATH:process.env.E2E_DATABASE_PATH,UPLOAD_DIR:'/tmp/picking-e2e-uploads',DEMO_PASSWORD:'testpassword123'},stdio:'pipe'});});
test('admin splits SKU stock across racks and staff packing deducts selected locations once',async({page})=>{
 const origin={origin:'http://127.0.0.1:3010'};
 await page.goto('/login');await page.getByLabel('Username').fill('admin.demo');await page.getByLabel('Password',{exact:true}).fill('testpassword123');await page.getByRole('button',{name:'Masuk ke gudang'}).click();await expect(page.getByRole('heading',{name:'Ringkasan gudang'})).toBeVisible();
 await page.goto('/admin/products');await page.getByLabel('SKU produk').fill('MULTI-E2E');await page.getByLabel('Nama barang',{exact:true}).fill('Produk dua rak');await page.getByLabel('Rak',{exact:true}).selectOption('1');await page.getByLabel('Ambalan',{exact:true}).selectOption('B');await page.getByLabel('Quantity',{exact:true}).fill('2');await page.getByRole('button',{name:'Tambah lokasi',exact:true}).click();await page.getByLabel('Rak 2',{exact:true}).selectOption('3');await page.getByLabel('Ambalan 2',{exact:true}).selectOption('D');await page.getByLabel('Quantity 2',{exact:true}).fill('3');await page.getByRole('button',{name:'Simpan barang'}).click();await expect(page.getByRole('status')).toContainText('berhasil disimpan');
 const products=await (await page.request.get('/api/products')).json();const product=products.find((p:{sku:string})=>p.sku==='MULTI-E2E');expect(product.locations).toHaveLength(2);expect(product.totalQuantity).toBe(5);
 const orders=await (await page.request.get('/api/orders')).json(),source=orders.find((o:{orderNumber:string})=>o.orderNumber==='DEMO-001');
 const created=await page.request.post('/api/orders',{headers:origin,data:{orderNumber:'INVENTORY-E2E',airwayBill:'INVENTORY-AWB',pdfFileId:source.pdfFileId,receiptPages:[1],items:[{productId:product.id,qty:3}]}});expect(created.ok()).toBeTruthy();const {id}=await created.json();
 await page.request.post('/api/auth/logout',{headers:origin});await page.goto('/login');await page.getByLabel('Username').fill('staff.demo');await page.getByLabel('Password',{exact:true}).fill('testpassword123');await page.getByRole('button',{name:'Masuk ke gudang'}).click();await expect(page.getByRole('heading',{name:'Ringkasan gudang'})).toBeVisible();await page.setViewportSize({width:390,height:844});await page.goto(`/orders/${id}`);await page.getByRole('button',{name:'Mulai picking'}).click();
 await page.getByLabel('Kode manual').fill('MULTI-E2E');await page.getByRole('button',{name:'Kirim kode'}).click();await expect(page.getByRole('alert').filter({hasText:'Pilih lokasi'})).toBeVisible();
 const select=page.getByLabel('Lokasi pengambilan MULTI-E2E');await select.selectOption(product.locations[0].id);await page.getByLabel('Kode manual').fill('MULTI-E2E');await page.getByRole('button',{name:'Kirim kode'}).click();await expect(page.getByRole('status')).toContainText('+1 unit');
 await select.selectOption(product.locations[1].id);await page.screenshot({path:'/tmp/picking-inventory-mobile.png',fullPage:true});
 for(let i=0;i<2;i++){await page.getByLabel('Kode manual').fill('MULTI-E2E');await page.getByRole('button',{name:'Kirim kode'}).click();if(i===0)await expect(page.getByText('2 / 3 unit',{exact:true})).toBeVisible();}
 await expect(page.getByRole('heading',{name:'Packing & resi'})).toBeVisible();const before=await (await page.request.get('/api/products')).json();expect(before.find((p:{id:string})=>p.id===product.id).totalQuantity).toBe(5);
 await page.getByLabel('Kode manual').fill('INVENTORY-AWB');await page.getByRole('button',{name:'Kirim kode'}).click();await expect(page.getByText('Order siap dikirim',{exact:true})).toBeVisible();
 const after=await (await page.request.get('/api/products')).json(),packed=after.find((p:{id:string})=>p.id===product.id);expect(packed.locations.map((l:{quantity:number})=>l.quantity)).toEqual([1,1]);expect(packed.totalQuantity).toBe(2);
 const repeated=await page.request.post(`/api/orders/${id}/scan`,{headers:origin,data:{kind:'airwayBill',code:'INVENTORY-AWB',requestId:crypto.randomUUID()}});expect(repeated.ok()).toBeTruthy();expect((await (await page.request.get('/api/products')).json()).find((p:{id:string})=>p.id===product.id).totalQuantity).toBe(2);
 await page.goto('/products?search=MULTI-E2E');await expect(page.getByRole('article')).toContainText('Total quantity: 2 unit');await expect(page.getByRole('article')).toContainText('Rak 3');
});
