import Link from 'next/link';
import { Clock3,ScanLine,PackageCheck,CheckCheck,Plus,FileUp,ArrowRight,MapPin } from 'lucide-react';
import { pageActor } from '@/lib/server-actor';
import { listOrders } from '@/lib/orders';
import { listRacks } from '@/lib/racks';
import { listProducts } from '@/lib/catalog';
import { OrderList } from '@/components/order-list';
import type { Status } from '@/lib/types';
export default async function Dashboard({searchParams}:{searchParams:Promise<{status?:string;search?:string}>}){
 const actor=await pageActor();const params=await searchParams;const all=listOrders(actor);const products=listProducts(actor);const valid=['waiting','picking','packing','completed'].includes(params.status||'');const orders=listOrders(actor,{status:valid?params.status as Status:undefined,search:params.search});
 const metrics=[{status:'waiting',label:'Menunggu picking',icon:Clock3,color:'amber',note:'Siap untuk diambil'},{status:'picking',label:'Sedang picking',icon:ScanLine,color:'blue',note:'Barang sedang dikumpulkan'},{status:'packing',label:'Menunggu packing',icon:PackageCheck,color:'violet',note:'Lengkapi paket & resi'},{status:'completed',label:'Order selesai',icon:CheckCheck,color:'emerald',note:'Sudah diverifikasi dengan resi'}];
 const racks=listRacks(actor);
 return <><div className="page-heading"><div><span className="eyebrow">OPERASIONAL HARI INI</span><h1>Ringkasan gudang</h1><p>Halo, {actor.name}. Mari siapkan order berikutnya.</p></div>{actor.role==='admin'&&<div className="heading-actions"><Link href="/admin/import" className="action-link secondary"><FileUp className="size-4"/>Import PDF</Link><Link href="/admin/orders/new" className="action-link"><Plus className="size-4"/>Order baru</Link></div>}</div><div className="metric-grid">{metrics.map(({status,label,icon:Icon,color,note})=><Link href={`/?status=${status}`} className="metric-card" key={status}><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><span className={`metric-icon ${color}`}><Icon className="size-[18px]"/></span></div><strong>{all.filter(o=>o.status===status).length.toString().padStart(2,'0')}</strong><span className="metric-note">{note}</span></Link>)}</div><section className="surface"><div className="section-heading"><div><h2>Antrean order</h2><p>Pantau setiap order dari picking hingga siap dikirim.</p></div><span className="subtle-pill">{orders.length} order</span></div><div className="queue-toolbar"><nav className="tabs" aria-label="Filter status">{[{value:'',label:'Semua'},{value:'waiting',label:'Menunggu'},{value:'picking',label:'Picking'},{value:'packing',label:'Packing'},{value:'completed',label:'Selesai'}].map(t=><Link key={t.value} href={t.value?`/?status=${t.value}`:'/'} className={params.status===t.value||!params.status&&!t.value?'selected':''}>{t.label}</Link>)}</nav><form className="queue-search"><input name="search" aria-label="Cari order atau resi" placeholder="Cari order atau resi…" defaultValue={params.search}/>{params.status&&<input name="status" type="hidden" value={params.status}/>}<button aria-label="Cari"><ArrowRight className="size-4"/></button></form></div><OrderList orders={orders}/></section><section className="location-summary"><div><span className="metric-icon emerald"><MapPin className="size-5"/></span><div><h3>Gudang tertata, picking lebih cepat.</h3><p>{products.filter(p=>p.active).length} SKU aktif tersebar di {racks.length} rak dan {racks.reduce((sum,r)=>sum+r.shelfCount,0)} ambalan.</p></div></div>{actor.role==='admin'&&<Link href="/admin/products">Atur barang & lokasi<ArrowRight className="size-4"/></Link>}</section></>;
}
