"use client";
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { LayoutDashboard,Package,Boxes,Users,FileUp,LogOut,Layers3,ArrowUpRight,ShieldCheck,ClipboardCheck } from 'lucide-react';
import { Button } from './ui/button';
import { api } from '@/lib/client';
import type { Actor } from '@/lib/types';
import { useState } from 'react';
export function AppShell({actor,children,rackCount,shelfCount}:{actor:Actor;children:React.ReactNode;rackCount:number;shelfCount:number}) {
 const path=usePathname(),router=useRouter();const [error,setError]=useState('');
 const links=[{href:'/',label:'Ringkasan',icon:LayoutDashboard},{href:'/products',label:'Daftar produk',icon:Boxes},{href:'/admin/stocktakes',label:'Stok opname',icon:ClipboardCheck},...(actor.role==='admin'?[{href:'/admin/orders',label:'Order',icon:Package},{href:'/admin/import',label:'Import PDF',icon:FileUp},{href:'/admin/products',label:'Barang & lokasi',icon:Boxes},{href:'/admin/staff',label:'Tim gudang',icon:Users}]:[])];
 return <div className="app-layout"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark"><Layers3 className="size-6"/></span><span>rakit<span className="brand-dot">.</span></span></Link><div className="sidebar-caption">WORKSPACE GUDANG</div><nav aria-label="Navigasi utama">{links.map(({href,label,icon:Icon})=><Link key={href} href={href} className={`nav-link ${path===href||href!=='/'&&path.startsWith(href)?'active':''}`}><Icon className="size-[18px]"/>{label}</Link>)}</nav><div className="sidebar-bottom"><div className="warehouse-note"><span className="online-dot"/>Gudang utama<p>{rackCount} rak · {shelfCount} ambalan</p></div><div className="user-block"><span className="avatar">{actor.name.slice(0,1).toUpperCase()}</span><div className="min-w-0"><strong>{actor.name}</strong><span>{actor.role==='admin'?'Administrator':'Staff gudang'}</span></div><Button variant="ghost" size="icon" aria-label="Keluar" onClick={async()=>{try{await api('/api/auth/logout',{method:'POST'});router.replace('/login');router.refresh();}catch(e){setError((e as Error).message);}}}><LogOut className="size-4"/></Button></div>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div></aside><div className="main-area"><header className="topbar"><div className="flex items-center gap-2"><span className="text-muted-foreground">Workspace</span><span className="text-slate-300">/</span><span>Gudang utama</span></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-emerald-700"/><span>{actor.role==='admin'?'Akses admin':'Akses staff'}</span><span className="small-avatar">{actor.name.slice(0,1)}</span><Button className="mobile-logout" variant="ghost" size="icon" aria-label="Keluar" onClick={async()=>{try{await api('/api/auth/logout',{method:'POST'});router.replace('/login');router.refresh();}catch(e){setError((e as Error).message);}}}><LogOut className="size-4"/></Button></div></header><main className="page-content">{children}</main><footer className="page-footer"><span>rakit. / Operasional gudang</span><span className="flex items-center gap-1">Ambil. Periksa. Kirim.<ArrowUpRight className="size-3"/></span></footer></div></div>;
}
