"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Boxes,Package,Plus,Pencil,MapPin,Trash2 } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { RackSettings } from './rack-settings';
import { shelfLabels } from '@/lib/locations';
import { api,upload } from '@/lib/client';
import type { Product,Rack } from '@/lib/types';
export function CatalogWorkspace({products,racks}:{products:Product[];racks:Rack[]}){
 const router=useRouter(),[editing,setEditing]=useState<Product|null>(null),[formKey,setFormKey]=useState(0),[search,setSearch]=useState(''),[rack,setRack]=useState<number|null>(null),[success,setSuccess]=useState('');
 const filtered=products.filter(p=>(!rack||p.locations.some(l=>l.rack===rack))&&`${p.sku} ${p.name}`.toLowerCase().includes(search.toLowerCase()));
 function edit(product:Product|null){setEditing(product);setFormKey(k=>k+1);setSuccess('');}
 return <><RackSettings racks={racks}/><div className="rack-grid">{racks.map(({id,name,shelfCount})=><button key={id} onClick={()=>setRack(rack===id?null:id)} className={`rack-card ${rack===id?'selected':''}`}><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-semibold"><Boxes className="size-4"/>{name}</span><span className="text-xs text-muted-foreground">{products.filter(p=>p.active&&p.locations.some(l=>l.rack===id)).length} SKU</span></div><div className="shelf-map">{shelfLabels(shelfCount).map(s=><span className={products.some(p=>p.active&&p.locations.some(l=>l.rack===id&&l.shelf===s))?'occupied':''} key={s}>{s}</span>)}</div></button>)}</div>
 <div className="admin-split"><section className="surface"><div className="section-heading"><div><h2>Master barang</h2><p>Satu SKU dapat memiliki stok di beberapa lokasi.</p></div><Button variant="outline" onClick={()=>edit(null)}><Plus/>Tambah</Button></div><div className="p-4"><Input aria-label="Cari SKU atau nama barang" placeholder="Cari SKU atau nama barang…" value={search} onChange={e=>setSearch(e.target.value)} className="h-10"/></div><div className="catalog-list">{filtered.length?filtered.map(p=><button key={p.id} onClick={()=>edit(p)} className={`catalog-row ${editing?.id===p.id?'selected':''}`}><span className="product-thumb">{p.photoFileId?<img src={`/api/files/${p.photoFileId}`} alt={p.name}/>:<Package className="size-6"/>}</span><span className="min-w-0 flex-1 text-left"><strong className="block truncate">{p.name}</strong><span className="mt-1 block font-mono text-xs text-muted-foreground">{p.sku}</span><span className="mt-2 block text-xs">Total: {p.totalQuantity===null?'quantity belum lengkap':`${p.totalQuantity} unit`}</span></span><span className="flex max-w-[45%] flex-wrap justify-end gap-1 text-right">{p.locations.map(l=><span key={l.id} className="location-tag">{l.rackName} · {l.shelf} · {l.quantity??'—'}</span>)}{!p.active&&<span className="block text-xs text-slate-400">Nonaktif</span>}</span><Pencil className="ml-2 size-4 shrink-0 text-muted-foreground"/></button>):<div className="empty-state"><Package/><h3>Barang belum tersedia</h3><p>Tambahkan SKU pertama untuk mulai menerima order.</p></div>}</div></section>
 <section className="surface form-surface h-fit"><h2 className="mb-1">{editing?'Edit barang':'Tambah barang'}</h2><p className="mb-6 text-sm text-muted-foreground">Foto dan QR mengikuti SKU. Isi quantity fisik per rak/ambalan.</p><CatalogForm key={formKey} product={editing} racks={racks} onSaved={()=>{setEditing(null);setFormKey(k=>k+1);setSuccess('Barang dan lokasi berhasil disimpan.');router.refresh();}}/>{success&&<p className="notice success mt-4" role="status">{success}</p>}</section></div></>;
}
type DraftLocation={id?:string;rack:number;shelf:string;quantity:string;reservedQuantity:number;expectedQuantity?:number|null};
function CatalogForm({product,racks,onSaved}:{product:Product|null;racks:Rack[];onSaved:()=>void}){
 const blank=():DraftLocation=>({rack:racks[0]?.id??1,shelf:'A',quantity:'0',reservedQuantity:0});
 const [locations,setLocations]=useState<DraftLocation[]>(product?product.locations.map(l=>({id:l.id,rack:l.rack,shelf:l.shelf,quantity:l.quantity===null?'':String(l.quantity),reservedQuantity:l.reservedQuantity,expectedQuantity:l.quantity})):[blank()]);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 function update(index:number,change:Partial<DraftLocation>){setLocations(rows=>rows.map((l,i)=>i===index?{...l,...change}:l));}
 return <form className="space-y-5" onSubmit={async e=>{
  e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);
  try{
   const photo=data.get('photo') as File,image=photo?.size?await upload(photo,'photo'):null;
   await api(product?`/api/products/${product.id}`:'/api/products',{method:product?'PATCH':'POST',body:JSON.stringify({sku:data.get('sku'),name:data.get('name'),photoFileId:image?.id||product?.photoFileId||undefined,active:data.get('active')==='on',locations:locations.map(l=>({id:l.id,rack:l.rack,shelf:l.shelf,quantity:Number(l.quantity),expectedQuantity:l.expectedQuantity}))})});onSaved();
  }catch(cause){setError((cause as Error).message);}finally{setBusy(false);}
 }}>
 <div><Label htmlFor="sku">SKU produk</Label><Input id="sku" name="sku" defaultValue={product?.sku} placeholder="Contoh: SKU-A" required className="mt-2 h-11"/></div>
 <div><Label htmlFor="product-name">Nama barang</Label><Input id="product-name" name="name" defaultValue={product?.name} placeholder="Nama barang" required className="mt-2 h-11"/></div>
 <div><Label htmlFor="photo">Foto barang</Label><Input id="photo" name="photo" type="file" accept="image/png,image/jpeg,image/webp" className="mt-2 h-11"/><p className="mt-2 text-xs text-muted-foreground">JPEG, PNG, WebP · maks. 5 MB. Foto disimpan per SKU.</p></div>
 <div><h3 className="mb-2 font-semibold">Lokasi & quantity</h3><p className="mb-3 text-xs text-muted-foreground">Quantity berkurang setelah scan resi packing. Unit yang sudah dipicking dicadangkan sampai packing selesai.</p>{product?.locations.some(l=>l.quantity===null)&&<p className="notice warning mb-3">Isi quantity barang lama berdasarkan stok fisik saat ini, termasuk unit yang sudah diambil untuk order yang belum selesai packing.</p>}
 <div className="space-y-3">{locations.map((l,index)=>{
  const shelves=shelfLabels(racks.find(r=>r.id===l.rack)?.shelfCount??0),suffix=index===0?'':` ${index+1}`;
  return <fieldset key={l.id??`new-${index}`} className="rounded-xl border p-3"><legend className="px-1 text-xs font-semibold">Lokasi {index+1}</legend><div className="grid grid-cols-2 gap-3"><div><Label htmlFor={`rack-${index}`}>{`Rak${suffix}`}</Label><select id={`rack-${index}`} className="native-select mt-2" value={l.rack} disabled={busy||l.reservedQuantity>0} onChange={e=>update(index,{rack:Number(e.target.value),shelf:'A'})}>{racks.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div><Label htmlFor={`shelf-${index}`}>{`Ambalan${suffix}`}</Label><select id={`shelf-${index}`} className="native-select mt-2" value={l.shelf} disabled={busy||l.reservedQuantity>0} onChange={e=>update(index,{shelf:e.target.value})}>{shelves.map(s=><option key={s} value={s}>Ambalan {s}</option>)}</select></div></div><div className="mt-3 flex items-end gap-2"><div className="flex-1"><Label htmlFor={`quantity-${index}`}>{`Quantity${suffix}`}</Label><Input id={`quantity-${index}`} type="number" required min={l.reservedQuantity} max={Number.MAX_SAFE_INTEGER} step={1} value={l.quantity} onChange={e=>update(index,{quantity:e.target.value})} disabled={busy} placeholder="Isi stok fisik" className="mt-2"/></div><Button type="button" variant="ghost" size="icon" aria-label={`Hapus lokasi ${index+1}`} disabled={busy||locations.length===1||l.reservedQuantity>0} onClick={()=>setLocations(rows=>rows.filter((_,i)=>i!==index))}><Trash2 className="size-4"/></Button></div>{l.reservedQuantity>0&&<p className="mt-2 text-xs text-amber-700">{l.reservedQuantity} unit dicadangkan. Lokasi terkunci sampai packing selesai.</p>}</fieldset>;
 })}</div><Button type="button" variant="outline" disabled={busy||locations.length>=100} onClick={()=>setLocations(rows=>[...rows,blank()])} className="mt-3"><Plus/>Tambah lokasi</Button></div>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="active" defaultChecked={product?.active??true}/>Barang aktif</label>{error&&<p className="notice error" role="alert">{error}</p>}<Button type="submit" disabled={busy} className="h-11 w-full"><MapPin className="size-4"/>{busy?'Menyimpan…':'Simpan barang'}</Button>
 </form>;
}
