"use client";
import { useState } from 'react';
import { FileUp,Sparkles,FileText,CheckCircle2 } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { OrderForm } from './order-form';
import { api,upload } from '@/lib/client';
import type { Product,ExtractedOrder } from '@/lib/types';
export function ImportWorkspace({products,configured}:{products:Product[];configured:boolean}) {
 const [file,setFile]=useState<File|null>(null),[stored,setStored]=useState<{id:string;pageCount:number|null}|null>(null),[orders,setOrders]=useState<ExtractedOrder[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[manual,setManual]=useState(false),[saved,setSaved]=useState<number[]>([]);
 return <div className="space-y-6"><section className="surface form-surface"><div className="import-intro"><span className="import-icon"><FileUp className="size-8"/></span><div><h2>Upload PDF order & resi</h2><p>Format boleh berbeda. AI membantu membaca; Anda memeriksa hasilnya.</p></div></div>{!configured&&<p className="notice warning mb-5">Gemini belum dikonfigurasi. Anda tetap dapat upload PDF lalu mengisi order secara manual.</p>}<Label htmlFor="import-pdf">PDF order</Label><Input id="import-pdf" type="file" accept="application/pdf" disabled={busy} className="mt-2 h-11" onChange={e=>{setFile(e.target.files?.[0]||null);setStored(null);setOrders([]);setSaved([]);setManual(false);setError('');}}/><div className="mt-5 flex flex-wrap gap-3"><Button disabled={!file||busy} className="h-11" onClick={async()=>{setBusy(true);setError('');try{const result=stored||await upload(file!,'pdf');setStored(result);const response=await api<{orders:ExtractedOrder[];error:string|null}>('/api/imports',{method:'POST',body:JSON.stringify({fileId:result.id})});setOrders(response.orders);if(response.error){setError(response.error);setManual(true);}}catch(e){setError((e as Error).message);setManual(true);}finally{setBusy(false);}}}><Sparkles className="size-4"/>{busy?'Membaca PDF…':'Baca PDF dengan AI'}</Button><Button variant="outline" disabled={!file||busy} className="h-11" onClick={async()=>{setBusy(true);setError('');try{const result=stored||await upload(file!,'pdf');setStored(result);setManual(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Isi manual dengan PDF ini</Button></div>{error&&<p role="alert" className="notice error mt-4">{error}</p>}{stored&&<a href={`/api/files/${stored.id}`} target="_blank" rel="noreferrer" className="mt-4 flex items-center gap-2 text-sm text-emerald-700"><FileText className="size-4"/>Lihat PDF sumber · {stored.pageCount} halaman</a>}</section>
 {orders.length>0&&<div className="review-note"><Sparkles className="size-5"/><div><strong>{orders.length} draf ditemukan</strong><p>Periksa nomor order, resi, SKU, qty, dan halaman resi. Draf belum masuk antrean.</p></div></div>}{orders.map((order,index)=><section key={index} className="surface form-surface"><h2 className="mb-5">Periksa order {index+1}</h2>{saved.includes(index)?<p className="notice success flex items-center gap-2"><CheckCircle2 className="size-4"/>Order tersimpan dan masuk antrean picking.</p>:<OrderForm products={products} extracted={order} pdfFileId={stored?.id} pageCount={stored?.pageCount} onSaved={()=>setSaved([...saved,index])}/>}</section>)}{manual&&stored&&<section className="surface form-surface"><h2 className="mb-5">Input manual dari PDF</h2><OrderForm products={products} pdfFileId={stored.id} pageCount={stored.pageCount}/></section>}
 </div>;
}
