"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Plus,Trash2,FileText,ArrowRight,Upload } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { api,upload } from '@/lib/client';
import type { Product,OrderDetail,ExtractedOrder } from '@/lib/types';
type Props={products:Product[];initialOrder?:OrderDetail;extracted?:ExtractedOrder;pdfFileId?:string;pageCount?:number|null;onSaved?:()=>void};
export function OrderForm({products,initialOrder,extracted,pdfFileId,pageCount,onSaved}:Props){
 const router=useRouter();const [orderNumber,setNumber]=useState(initialOrder?.orderNumber||extracted?.orderNumber||'');const [airwayBill,setBill]=useState(initialOrder?.airwayBill||extracted?.airwayBill||'');
 const [fileId,setFile]=useState(initialOrder?.pdfFileId||pdfFileId||'');const [pages,setPages]=useState((initialOrder?.receiptPages||extracted?.receiptPages||(pageCount===1?[1]:[])).join(', '));const [count,setCount]=useState(pageCount||null);
 const [items,setItems]=useState(initialOrder?.items.map(i=>({productId:i.productId,qty:i.qty,sourceSku:i.sku}))||extracted?.items.map(i=>({productId:products.find(p=>p.sku===i.sku.trim()&&p.active)?.id||'',qty:i.qty,sourceSku:i.sku}))||[{productId:'',qty:1,sourceSku:''}]);
 const [busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');const frozen=!!initialOrder&&initialOrder.status!=='waiting';
 return <form className="space-y-6" onSubmit={async e=>{e.preventDefault();if(uploading)return;setBusy(true);setError('');try{const payload={orderNumber,airwayBill,pdfFileId:fileId||undefined,receiptPages:pages.trim()?pages.split(',').map(p=>Number(p.trim())):[],items:items.map(({productId,qty})=>({productId,qty}))};const result=await api<{id:string}>(initialOrder?`/api/orders/${initialOrder.id}`:'/api/orders',{method:initialOrder?'PATCH':'POST',body:JSON.stringify(payload)});if(onSaved)onSaved();else {router.push(`/orders/${initialOrder?.id||result.id}`);router.refresh();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="order-number">Nomor order</Label><Input id="order-number" value={orderNumber} onChange={e=>setNumber(e.target.value)} placeholder="Contoh: ORD-2026-001" required readOnly={frozen} className="mt-2 h-11"/></div><div><Label htmlFor="airway-bill">Nomor resi / airway bill</Label><Input id="airway-bill" value={airwayBill} onChange={e=>setBill(e.target.value)} placeholder="Boleh dilengkapi sebelum packing" className="mt-2 h-11"/></div></div>
 <div><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Barang dalam order</h3>{!frozen&&<Button type="button" variant="outline" onClick={()=>setItems([...items,{productId:'',qty:1,sourceSku:''}])}><Plus/>Tambah barang</Button>}</div><div className="space-y-3">{items.map((item,index)=><div key={index} className="order-item-input"><div className="min-w-0 flex-1"><Label htmlFor={`product-${index}`}>SKU / barang {index+1}</Label><select id={`product-${index}`} className="native-select mt-2" value={item.productId} disabled={frozen} required onChange={e=>setItems(items.map((x,i)=>i===index?{...x,productId:e.target.value}:x))}><option value="">{item.sourceSku?`Petakan SKU: ${item.sourceSku}`:'Pilih barang'}</option>{products.filter(p=>p.active||p.id===item.productId).map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select>{item.sourceSku&&!item.productId&&<p className="mt-1 text-xs text-amber-700">SKU “{item.sourceSku}” belum cocok. Pilih barang atau daftarkan SKU terlebih dahulu.</p>}</div><div className="w-24 shrink-0"><Label htmlFor={`qty-${index}`}>Qty</Label><Input id={`qty-${index}`} type="number" min="1" step="1" value={item.qty} required disabled={frozen} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,qty:Number(e.target.value)}:x))} className="mt-2 h-11"/></div>{!frozen&&<Button type="button" variant="ghost" size="icon" className="mt-6" aria-label={`Hapus barang ${index+1}`} disabled={items.length===1} onClick={()=>setItems(items.filter((_,i)=>i!==index))}><Trash2 className="size-4"/></Button>}</div>)}</div>{!products.length&&<p className="notice error mt-3">Daftarkan barang di menu Barang & lokasi sebelum membuat order.</p>}{frozen&&<p className="mt-2 text-xs text-muted-foreground">Picking sudah dimulai. SKU dan qty terkunci; data resi masih dapat dilengkapi.</p>}</div>
 <section className="rounded-xl border bg-slate-50/60 p-4"><h3 className="mb-1 flex items-center gap-2 font-semibold"><FileText className="size-4"/>Dokumen resi</h3><p className="mb-4 text-xs text-muted-foreground">PDF untuk dicetak staff. Maksimal 15 MB.</p><Label htmlFor="receipt-file"><Upload className="size-4"/>{fileId?'Ganti PDF resi':'Upload PDF resi'}</Label><Input id="receipt-file" type="file" accept="application/pdf" disabled={busy||uploading} className="mt-2 h-11 bg-white" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setError('');try{const result=await upload(file,'pdf');setFile(result.id);setCount(result.pageCount);setPages(result.pageCount===1?'1':'');}catch(e){setError((e as Error).message);}finally{setUploading(false);}}}/>{uploading&&<p className="mt-2 text-sm">Mengunggah PDF…</p>}{fileId&&<><a className="mt-3 inline-block text-sm text-emerald-700 underline" href={`/api/files/${fileId}`} target="_blank" rel="noreferrer">Lihat PDF sumber{count?` (${count} halaman)`:''}</a><div className="mt-4"><Label htmlFor="receipt-pages">Halaman resi untuk order ini</Label><Input id="receipt-pages" value={pages} onChange={e=>setPages(e.target.value)} placeholder="Contoh: 1, 3" required className="mt-2 h-11 bg-white"/><p className="mt-2 text-xs text-muted-foreground">Nomor halaman dimulai dari 1. Hanya halaman ini yang dicetak.</p></div></>}</section>
 {error&&<p role="alert" className="notice error">{error}</p>}<div className="flex justify-end"><Button type="submit" disabled={busy||uploading||!products.length} className="h-11 px-5">{busy?'Menyimpan…':initialOrder?'Simpan perubahan':'Simpan order'}<ArrowRight/></Button></div>
 </form>;
}
