import Link from 'next/link';
import { Package,ArrowUpRight } from 'lucide-react';
import { Badge } from './ui/badge';
import { statusLabels } from '@/lib/client';
import type { OrderDetail } from '@/lib/types';
export function StatusBadge({status}:{status:OrderDetail['status']}){return <Badge variant="outline" className={`status-badge ${status}`}><span className="size-1.5 rounded-full bg-current"/>{statusLabels[status]}</Badge>;}
export function OrderList({orders}:{orders:OrderDetail[]}){
 if(!orders.length)return <div className="empty-state"><span className="empty-icon"><Package className="size-7"/></span><h3>Belum ada order di sini</h3><p>Order yang masuk akan muncul di antrean ini.</p></div>;
 return <><div className="desktop-orders"><table className="orders-table"><thead><tr><th>ORDER / RESI</th><th>BARANG</th><th>PROGRES PICKING</th><th>STAFF</th><th>STATUS</th><th></th></tr></thead><tbody>{orders.map(o=>{const qty=o.items.reduce((n,i)=>n+i.qty,0),picked=o.items.reduce((n,i)=>n+i.pickedQty,0);return <tr key={o.id}><td><Link className="order-number" href={`/orders/${o.id}`}>{o.orderNumber}</Link><span className="cell-caption">{o.airwayBill||'Resi belum diisi'}</span></td><td><strong>{o.items.length} SKU</strong><span className="cell-caption">{qty} unit barang</span></td><td><div className="flex items-center gap-3"><div className="progress-track w-24"><div style={{width:`${picked/qty*100}%`}}/></div><span className="text-xs text-muted-foreground">{picked}/{qty}</span></div></td><td className="text-muted-foreground">{o.assigneeName||'Belum ditugaskan'}</td><td><StatusBadge status={o.status}/></td><td><Link href={`/orders/${o.id}`} aria-label={`Buka order ${o.orderNumber}`}><ArrowUpRight className="size-4 text-slate-400"/></Link></td></tr>;})}</tbody></table></div><div className="mobile-orders">{orders.map(o=><Link href={`/orders/${o.id}`} key={o.id} aria-label={o.orderNumber} className="mobile-order"><div className="flex items-center justify-between gap-2"><strong>{o.orderNumber}</strong><StatusBadge status={o.status}/></div><p>{o.items.length} SKU · {o.items.reduce((n,i)=>n+i.qty,0)} unit</p><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{o.assigneeName||'Siap diambil'}</span><ArrowUpRight className="size-4"/></div></Link>)}</div></>;
}
