"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { UserPlus,KeyRound } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { api } from '@/lib/client';
type User={id:string;name:string;username:string;role:string;active:number};
export function StaffWorkspace({users}:{users:User[]}){
 const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reset,setReset]=useState<User|null>(null);
 async function update(id:string,input:unknown){setBusy(true);setError('');try{await api(`/api/staff/${id}`,{method:'PATCH',body:JSON.stringify(input)});setMessage('Akun berhasil diperbarui.');setReset(null);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="admin-split"><section className="surface"><div className="section-heading"><h2>Anggota tim</h2><span className="subtle-pill">{users.length} akun</span></div><div className="divide-y">{users.map(u=><div key={u.id} className="staff-row"><span className="avatar">{u.name.slice(0,1)}</span><div className="min-w-0 flex-1"><strong className="block truncate">{u.name}</strong><span className="text-xs text-muted-foreground">{u.username} · {u.role==='admin'?'Admin':'Staff'} · {u.active?'Aktif':'Nonaktif'}</span></div><Button variant="ghost" size="icon" aria-label={`Reset password ${u.name}`} onClick={()=>setReset(u)}><KeyRound className="size-4"/></Button><Button variant="outline" disabled={busy} onClick={()=>void update(u.id,{active:!u.active})}>{u.active?'Nonaktifkan':'Aktifkan'}</Button></div>)}</div>{reset&&<form className="m-5 space-y-3 border-t pt-4" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void update(reset.id,{password:data.get('password')});}}><Label htmlFor="reset-password">Password baru untuk {reset.name}</Label><Input id="reset-password" name="password" type="password" minLength={10} required autoComplete="new-password"/><Button type="submit" disabled={busy}>Simpan password</Button><Button type="button" variant="ghost" onClick={()=>setReset(null)}>Batal</Button></form>}{error&&<p role="alert" className="notice error m-5">{error}</p>}{message&&<p role="status" className="notice success m-5">{message}</p>}</section><section className="surface form-surface h-fit"><h2>Tambah staff</h2><p className="mb-6 mt-1 text-sm text-muted-foreground">Staff dapat picking, scan, dan packing.</p><form className="space-y-5" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setError('');try{await api('/api/staff',{method:'POST',body:JSON.stringify({name:data.get('name'),username:data.get('username'),password:data.get('password')})});form.reset();setMessage('Staff baru berhasil dibuat.');router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div><Label htmlFor="staff-name">Nama staff</Label><Input name="name" id="staff-name" className="mt-2 h-11" required/></div><div><Label htmlFor="staff-username">Username staff</Label><Input name="username" id="staff-username" className="mt-2 h-11" required minLength={3} autoComplete="off"/></div><div><Label htmlFor="staff-password">Password awal</Label><Input name="password" id="staff-password" type="password" className="mt-2 h-11" required minLength={10} autoComplete="new-password"/><p className="mt-2 text-xs text-muted-foreground">Minimal 10 karakter.</p></div><Button type="submit" disabled={busy} className="h-11 w-full"><UserPlus className="size-4"/>{busy?'Menyimpan…':'Tambah staff'}</Button></form></section></div>;
}
